config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about' , to: 'pages#about'
    resources :articles
    # , only: [:show, :index, :new, :create, :edit, :update, :destroy]
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/category.rb
class Category < ApplicationRecord
validates :name, presence: true, length: { minimum: 3, maximum: 25 }
validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX} 
    has_secure_password 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user

    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path status: :see_other
        end

    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy ]
    def show
       


    end

    def index

        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new

        @article = Article.new

    end
    def edit
       

    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        @article.user = current_user
        if @article.save
            redirect_to @article
       else
        render 'new'
           
       end
    end

    def update
        
        if @article.update(params.require(:article).permit(:title, :description))
            flash[:notice] = "Article was updated successfully."
            redirect_to @article

        else
            render 'edit'
        end
    end 

    def destroy
        
        @article.destroy
        redirect_to articles_path,status: :see_other

    end

    private

    def set_article
        @article = Article.find(params[:id])

    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def new
      @category = Category.new
    end
  
    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "Category was successfully created"
        redirect_to @category
      else
        render 'new'
      end
    end
  
    
    def index
    end
    def show

    end
  
    private
  
    def category_params
      params.require(:category).permit(:name)
    end
  end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end


    def about
        
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path, status: :see_other
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    def new
        @user = User.new
    end
    def edit
        
    end

    def update
        
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else
            render 'edit'
        end
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully sign up"
            redirect_to articles_path
        else
            render 'new' 
        end

    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted"
        redirect_to articles_path, status: :see_other

    end
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)

    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
        flash[:alert]  = "You can only edit or delete your own account"
        redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80 })
      email_address = user.email.downcase   
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username)
    end
    
    

    
end

app/views/articles/_article.html.erb
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan = "3">Actions</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.title%></td>
                <td><%= article.description%></td>
                <td><%= link_to 'View', article_path(article)%></td>
                <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                    <td><%= link_to 'Edit', edit_article_path(article)%></td>
                    <td><%= link_to 'Delete', article_path(article),  data: { "turbo-method": :delete, turbo_confirm: "Are you sure?"} %></td> 
                <%end%>
               
            </tr>
        <% end %>
    </tbody>
</table>
<p>
    <%= link_to 'Create new article', new_article_path%>
</p> 

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

    <h2>The following errors prevented the article from being saved </h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @article, local: true, data: { turbo: false }) do |f| %>

<%# <%= form_with(model: @article, local: true, data: { turbo: false }) do |f| %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title%>
    </p>

    <p>
        <%= f.label :description%><br/>
        <%= f.text_area :description %> 
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>editing article</h1>

<%= render 'form'%>
<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Listing all Articles</h1>
<div class="flickr_pagination">
       
        <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>


<div class="flickr_pagination">
       
        <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1>Creating new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Show article details</h1>


<p><strong>Title: </strong><%=@article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit' ,edit_article_path(@article) %> |
    <%= link_to 'Delete', article_path(@article),  data: { "turbo-method": :delete, turbo_confirm: "Are you sure?"}%>
<% end %>
<%= link_to 'Return to articles listing', articles_path %>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>

    <%= msg%>
<% end %>

app/views/layouts/_navigate.html.erb
<div class="navbar">
    <%= link_to "ALPHA-BLOG", root_path %>
    <%= link_to "Bloggers", users_path %>
    <div class="dropdown">
        <button class="dropbtn">Articles 
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
        <% if logged_in? %>
            <%= link_to 'Create Article', new_article_path %>
        <% end %>
            <%= link_to "View Articles", articles_path %>
            
        </div>   
    </div> 
    <% if logged_in? %>
    <div class="dropdown">
        <button class="dropbtn"><%= "(Admin)" if current_user.admin? %><%= current_user.username %>
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
        <%= link_to 'View your profile', user_path(current_user) %>
        <%= link_to "Edit your profile", edit_user_path(current_user) %>
        <%= link_to "Delete profile", user_path(current_user), data: { "turbo-method": :delete ,confirm: "Are you sure?" }%>
        </div>   
    </div> 
        <%= link_to "Log Out", logout_path, data: { "turbo-method": :delete } %>
    <% else %>
        <%= link_to "Log In", login_path %>
        <%= link_to "Sign Up", signup_path %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/navigate' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<%# <body style="text-align: center !important; width: 60%; margin: 0 auto; margin: auto !important;"> %>
<h1 style="text-align: center !important"> Welcome to the Homepage </h1>

<%=link_to 'Articles listing', articles_path %> ||
<%= link_to 'About Page', about_path %> ||
<%= link_to 'Sign Up to the website', signup_path %> ||
<%= link_to 'Log in', login_path %>
<%# </body> %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>

    <h2>The following errors prevented the article from being saved </h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @user,  local: true, data: { turbo: false }) do |f| %>

<%# <%= form_with(model: @user, local: true, data: { turbo: false }) do |f| %>
    <p>
        <%= f.label :username %><br/>
        <%= f.text_field :username%>
    </p>

    <p>
        <%= f.label :email %><br/>
        <%= f.email_field :email %> 
    </p>
    <p>
        <%= f.label :password %><br/>
        <%= f.password_field :password %> 
    </p>
    <p>
        <%= f.submit(@user.new_record? ? "Sign Up" :"Update account") %>
    </p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 style="text-align:center;">Alpha Bloggers</h1>

 <div class="flickr_pagination">
       
        <%= will_paginate @users, :container => false %>
</div>

<style>
table, th, td {
  border: 1px solid black;
  margin: 0px auto;
  text-align: center;
}
</style>


<table>
    <thead>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Articles</th>
            <th>Joined</th>
            <th colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= pluralize(user.articles.count, "article")%></td>
            <td><%= time_ago_in_words(user.created_at) %> ago</td>
            <% if logged_in? %> 
                 <td><%= link_to 'Show', user_path(user) %></td>
                <% if user == current_user %>
                    <td><%= link_to 'Edit Profile', edit_user_path(user) %></td>
                   
                <% end %>
                <% if current_user.admin? %>
                    <td><%= link_to "Delete User", user_path(user), data: { "turbo-method": :delete ,confirm: "Are you sure you want to delete the user and its associations ?" } %></td>

                <% end %>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>
 <div class="flickr_pagination">
       
        <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %> 's profile <h1>

<%= gravatar_for @user, size: 200 %>
<% if logged_in? && @user == current_user %>

    <%= link_to "Edit your profile", edit_user_path(@user)%>
<% end %>

<h1>Articles<h1>
<div class="flickr_pagination">
       
        <%= will_paginate @articles, :container => false %>
</div>


<%= render 'articles/article' %>


<div class="flickr_pagination">
       
        <%= will_paginate @articles, :container => false %>
</div>